version: '3'
services:
  web:
    build: .
    ports:
      - "8082:80"
    volumes:
      - .:/code
    depends_on:
      - mongo
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-m5", "-f", "http://localhost/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
  mongo:
    image: "mvertes/alpine-mongo"
